
<?php
require_once( 'dbconnect.php');
$a = $_GET['id'];
$result = mysql_query("select * from course_details where course_id='$a'")
        or die(mysql_error());
if ($row = mysql_fetch_array($result)) {
    $b = $row['course_name'] ;

    echo "<div><br><br><span class=navigation_link1>You are here: </sapn><a href=facindex.php?page=fachome class="."navigation_link> Home&nbsp&nbsp;&raquo; </a>  $b   </div>";
}
?>

<br><br>
<div class="course_options">
<br><a href="facindex.php?page=enroll&search=&id=<?php echo $_GET["id"]; ?>"> Enroll </a>
<br><a href="facindex.php?page=show&id=<?php echo $_GET["id"]; ?>&search="> Show enrolled students </a>
<br><a href="facindex.php?page=alter1&id=<?php echo $_GET["id"]; ?>"> Add and Cancel Classes </a>
<br><a href="facindex.php?page=class_attend&id=<?php echo $_GET["id"]; ?>"> Show Class Attendace </a>
</div>
