<?php echo "<div><br><br><span class=navigation_link1>You are here: </sapn><a href=adminindex.php?page=adminhome class="."navigation_link> Home&nbsp&nbsp;&raquo; </a><a href=adminindex.php?page=manage_course class="."navigation_link> Manage Courses&nbsp&nbsp;&raquo; </a> Add Course   </div>"; ?>

<br>

<div class=course_options>
<div class="errors"><ul>
<?php require 'dbconnect.php';

if(array_key_exists('save', $_POST))
{
	$empty_string_init = "\"    \" ";

	// #classes on that day
	$sun_count   = 0;   
	$mon_count   = 0;   
	$tue_count   = 0;
	$wed_count   = 0;
	$thu_count   = 0;
	$fri_count   = 0;
	$sat_count   = 0;

	//Sunday initialization 
	$sun1_start  = ( $_POST['sun_time1_start'] != "" ) ? $_POST['sun_time1_start'] : $empty_string_init;
	$sun1_end    = ( $_POST['sun_time1_end']   != "" ) ? $_POST['sun_time1_end']   : $empty_string_init;
	$sun2_start  = ( $_POST['sun_time2_start'] != "" ) ? $_POST['sun_time2_start'] : $empty_string_init;
	$sun2_end    = ( $_POST['sun_time2_end']   != "" ) ? $_POST['sun_time2_end']   : $empty_string_init;
	$sun3_start  = ( $_POST['sun_time3_start'] != "" ) ? $_POST['sun_time3_start'] : $empty_string_init;
	$sun3_end    = ( $_POST['sun_time3_end']   != "" ) ? $_POST['sun_time3_end']   : $empty_string_init;

	//Monday initialization   
	$mon1_start  = ( $_POST['mon_time1_start'] != "" ) ? $_POST['mon_time1_start'] : $empty_string_init;
	$mon1_end    = ( $_POST['mon_time1_end']   != "" ) ? $_POST['mon_time1_end']   : $empty_string_init;
	$mon2_start  = ( $_POST['mon_time2_start'] != "" ) ? $_POST['mon_time2_start'] : $empty_string_init;
	$mon2_end    = ( $_POST['mon_time2_end']   != "" ) ? $_POST['mon_time2_end']   : $empty_string_init;
	$mon3_start  = ( $_POST['mon_time3_start'] != "" ) ? $_POST['mon_time3_start'] : $empty_string_init;
	$mon3_end    = ( $_POST['mon_time3_end']   != "" ) ? $_POST['mon_time3_end']   : $empty_string_init;

	//Tuesday initialization
	$tue1_start  = ( $_POST['tue_time1_start'] != "" ) ? $_POST['tue_time1_start'] : $empty_string_init;
	$tue1_end  = ( $_POST['tue_time1_end']     != "" ) ? $_POST['tue_time1_end']   : $empty_string_init;
	$tue2_start  = ( $_POST['tue_time2_start'] != "" ) ? $_POST['tue_time2_start'] : $empty_string_init;
	$tue2_end  = ( $_POST['tue_time2_end']     != "" ) ? $_POST['tue_time2_end']   : $empty_string_init;
	$tue3_start  = ( $_POST['tue_time3_start'] != "" ) ? $_POST['tue_time3_start'] : $empty_string_init;
	$tue3_end    = ( $_POST['tue_time3_end']   != "" ) ? $_POST['tue_time3_end']   : $empty_string_init;

	//Wednesday initialization
	$wed1_start  = ( $_POST['wed_time1_start'] != "" ) ? $_POST['wed_time1_start'] : $empty_string_init;
	$wed1_end  = ( $_POST['wed_time1_end']     != "" ) ? $_POST['wed_time1_end']   : $empty_string_init;
	$wed2_start  = ( $_POST['wed_time2_start'] != "" ) ? $_POST['wed_time2_start'] : $empty_string_init;
	$wed2_end  = ( $_POST['wed_time2_end']     != "" ) ? $_POST['wed_time2_end']   : $empty_string_init;
	$wed3_start  = ( $_POST['wed_time3_start'] != "" ) ? $_POST['wed_time3_start'] : $empty_string_init;
	$wed3_end    = ( $_POST['wed_time3_end']   != "" ) ? $_POST['wed_time3_end']   : $empty_string_init;

	//Thursday initialization
	$thu1_start  = ( $_POST['thu_time1_start'] != "" ) ? $_POST['thu_time1_start'] : $empty_string_init;
	$thu1_end  = ( $_POST['thu_time1_end']     != "" ) ? $_POST['thu_time1_end']   : $empty_string_init;
	$thu2_start  = ( $_POST['thu_time2_start'] != "" ) ? $_POST['thu_time2_start'] : $empty_string_init;
	$thu2_end  = ( $_POST['thu_time2_end']     != "" ) ? $_POST['thu_time2_end']   : $empty_string_init;
	$thu3_start  = ( $_POST['thu_time3_start'] != "" ) ? $_POST['thu_time3_start'] : $empty_string_init;
	$thu3_end    = ( $_POST['thu_time3_end']   != "" ) ? $_POST['thu_time3_end']   : $empty_string_init;

	//Friday initialization
	$fri1_start  = ( $_POST['fri_time1_start'] != "" ) ? $_POST['fri_time1_start'] : $empty_string_init;
	$fri1_end  = ( $_POST['fri_time1_end']     != "" ) ? $_POST['fri_time1_end']   : $empty_string_init;
	$fri2_start  = ( $_POST['fri_time2_start'] != "" ) ? $_POST['fri_time2_start'] : $empty_string_init;
	$fri2_end  = ( $_POST['fri_time2_end']     != "" ) ? $_POST['fri_time2_end']   : $empty_string_init;
	$fri3_start  = ( $_POST['fri_time3_start'] != "" ) ? $_POST['fri_time3_start'] : $empty_string_init;
	$fri3_end    = ( $_POST['fri_time3_end']   != "" ) ? $_POST['fri_time3_end']   : $empty_string_init;

	//Saturday initialization
	$sat1_start  = ( $_POST['sat_time1_start'] != "" ) ? $_POST['sat_time1_start'] : $empty_string_init;
	$sat1_end    = ( $_POST['sat_time1_end']   != "" ) ? $_POST['sat_time1_end']   : $empty_string_init;
	$sat2_start  = ( $_POST['sat_time2_start'] != "" ) ? $_POST['sat_time2_start'] : $empty_string_init;
	$sat2_end    = ( $_POST['sat_time2_end']   != "" ) ? $_POST['sat_time2_end']   : $empty_string_init;
	$sat3_start  = ( $_POST['sat_time3_start'] != "" ) ? $_POST['sat_time3_start'] : $empty_string_init;
	$sat3_end    = ( $_POST['sat_time3_end']   != "" ) ? $_POST['sat_time3_end']   : $empty_string_init;


	//for iterating through all fields
	$index = array(
					$sun1_start , $sun1_end , $sun2_start , $sun2_end , $sun3_start , $sun3_end ,
					$mon1_start , $mon1_end , $mon2_start , $mon2_end , $mon3_start , $mon3_end ,
					$tue1_start , $tue1_end , $tue2_start , $tue2_end , $tue3_start , $tue3_end ,
					$wed1_start , $wed1_end , $wed2_start , $wed2_end , $wed3_start , $wed3_end ,
					$thu1_start , $thu1_end , $thu2_start , $thu2_end , $thu3_start , $thu3_end ,
					$fri1_start , $fri1_end , $fri2_start , $fri2_end , $fri3_start , $fri3_end ,
					$sat1_start , $sat1_end , $sat2_start , $sat2_end , $sat3_start , $sat3_end 
				  );
			  
	//for iterating through the days			  
	$day   = array ($sun_count , $mon_count , $tue_count , $wed_count , $thu_count , $fri_count , $sat_count);

	//  for index array = 7 days * 6 fields = 28 text-boxes
	$i=0;

	//  for day array   = 7    
	$j=0;   

	while ( $i  < 42 )
	{
		//if schedule one has class
		if (( $index[$i] != $empty_string_init ) and ($index[$i+1] != $empty_string_init)) 
		{
			$day[$j]++;
		}

		//if schedule two has class
		if (( $index[$i+2] != $empty_string_init ) and ($index[$i+3] != $empty_string_init)) 
		{
			$day[$j]++;
		}
		
		//if schedule two has class
		if (( $index[$i+4] != $empty_string_init ) and ($index[$i+5] != $empty_string_init)) 
		{
			$day[$j]++;
		}
		
		$i = $i + 6;
		$j = $j + 1 ;
	}


	//assigning #classes to variables
	$sun_count = $day[0];
	$mon_count = $day[1];
	$tue_count = $day[2];
	$wed_count = $day[3];
	$thu_count = $day[4];
	$fri_count = $day[5];
	$sat_count = $day[6];

	echo "<br>";

	$sun = "Sunday";
	$mon = "Monday";
	$tue = "Tuesday";
	$wed = "Wednesday";
	$thu = "Thursday";
	$fri = "Friday";
	$sat = "Saturday";

	$c_id   = $_POST['CourseID'];	//course id
	$c_nm   = $_POST['Name'];		//name of course
	$fac_id = $_POST['FacultyID'];	//faculty assigned
	$st_dt  = $_POST['StartDate'];	//starting date of course
	$fn_dt  = $_POST['FinishDate'];	//finishing date


	//inserting information about course in course_details table
	$query = "insert into course_details values ('$c_nm','$c_id','$fac_id','$st_dt','$fn_dt')";
	$result = mysql_query($query) ;

	//if entry in table fails : i.e. course already exists or already registered
	if (!$result)
	{
		echo "<li>Course Id already registered</li>";
	}
	else
	{
		$query =  "insert into course_schedule values ('$c_id','$sun','$sun1_start','$sun1_end','$sun2_start','$sun2_end','$sun3_start','$sun3_end','$sun_count')";
		$result = mysql_query($query) or die(mysql_error());
		
		$query =  "insert into course_schedule values('$c_id','$mon','$mon1_start','$mon1_end','$mon2_start','$mon2_end','$mon3_start','$mon3_end','$mon_count')";
		$result = mysql_query($query) or die(mysql_error());

		$query =  "insert into course_schedule values ('$c_id','$tue','$tue1_start','$tue1_end','$tue2_start','$tue2_end','$tue3_start','$tue3_end','$tue_count')";
		$result = mysql_query($query) or die(mysql_error());

		$query =  "insert into course_schedule values ('$c_id','$wed','$wed1_start','$wed1_end','$wed2_start','$wed2_end','$wed3_start','$wed3_end','$wed_count')";
		$result = mysql_query($query) or die(mysql_error());

		$query =  "insert into course_schedule values ('$c_id','$thu','$thu1_start','$thu1_end','$thu2_start','$thu2_end','$thu3_start','$thu3_end','$thu_count')";
		$result = mysql_query($query) or die(mysql_error());

		$query =  "insert into course_schedule values ('$c_id','$fri','$fri1_start','$fri1_end','$fri2_start','$fri2_end','$fri3_start','$fri3_end','$fri_count')";
		$result = mysql_query($query) or die(mysql_error());

		$query =  "insert into course_schedule values ('$c_id','$sat','$sat1_start','$sat1_end','$sat2_start','$sat2_end','$sat3_start','$sat3_end','$sat_count')";
		$result = mysql_query($query) or die(mysql_error());

		echo "<li>".$c_nm . " ( ". $c_id .") has been added successfully";
	}  

	unset($_POST['save']);
		
} 


if(array_key_exists('cancel', $_POST))
{	
	echo "<li>"."No changes have been made to database";
	unset($_POST['cancel']);
}

?>
</ul>
</div>


<?php 
//following form for taking input from admin for creating new course 
?>



<form name="add" action="#" method="post" id="add_course" onsubmit="return validation(this)">
    <fieldset>
    <div id="left">
        <div class="field">
             <label>Course ID</label> 
             <input type="text" name="CourseID" /> 
        </div>
        <br>
        <div class="field">
             <label>Course Name</label> 
             <input type="text" name="Name" /> 
        </div>       
        <br>
        <div class="field">
             <label>Faculty ID</label> 
				<?php 
                        $query = "
                                    SELECT id ,name  
                                    FROM  faculty f , registered r
                                    WHERE id = id_no ;
                                    ";
                        $result = mysql_query($query) or die(mysql_error());
                ?>
             
             <select name="FacultyID" >
                <?php                       
                        while ($row = mysql_fetch_array($result))
                        {
                              echo "<option value=".$row['id']."> ". $row['name'] ."  </option>";
                        }
                 ?>
             </select>
        </div>        
        <br>
        <br>
        <br>
        <div class="field">
             <label>Start Date</label> 
             <input type="Text" name="StartDate" value="" class="datepicker"> 
        </div>
		<br>
        <div class="field">
             <label>Finish Date</label> 
             <input type="Text" name="FinishDate" value="" class="datepicker"> 
        </div>
		<br>
	</div>
    <br> 
     
      
      
    <div >
        <p> Schedule for the whole week </p>
        <br>
                
		
        <br>

		<!-- Monday -->
		<div class="field">
			<label>Monday </label> 
			<input type="Text" class="time1"  name="mon_time1_start" value="" id="Mon1"> 
			to
			<input type="Text" class="time1"  name="mon_time1_end" value=""> 
			<input id="Mon" type="button" value="  +1 Slot  " onclick="show(this ,'mon2','mon3');" /><br>
        </div>
        <div id="mon2" class="field">
            <label></label>
            <input type="Text" class="time1" name="mon_time2_start" id="mon_sec_st" value=""> 
            to
			<input type="Text" class="time1"  name="mon_time2_end"  id="mon_sec_fn" value="">
            <input id="Mon" type="button" value="  +1 Slot  " onclick="show(this ,'mon3','mon3');" /><br>
		</div>
		<div id="mon3" class="field">
            <label></label>
            <input type="Text" class="time1" name="mon_time3_start" id="mon_thr_st" value=""> 
            to
			<input type="Text" class="time1"  name="mon_time3_end"  id="mon_thr_fn" value=""> <br>
        </div>
		<br>  
		<label></label>
		<label1></label1>
        &nbsp;
		<input type="button" name="copy_slots" id="copy_slots" value=" Copy for other slots " onclick="copy();"/>
		<br>
		<br>
		
		
		<!-- Tuesday -->
		<div class="field">
            <label>Tuesday </label> 
            <input type="Text" name="tue_time1_start" value="" class="time1"> 
            to
			<input type="Text"  class="time1" name="tue_time1_end" value=""> 
            <input id="Tue" type="button" value="  +1 Slot  " onclick="show(this , 'tue2' , 'tue3');" /><br> 
        </div>
        
		<div id="tue2" class="field">          
            <label></label>
            <input type="Text" class="time1"  name="tue_time2_start" id="tue_sec_st" value=""> 
            to
			<input type="Text"  class="time1" name="tue_time2_end" id="tue_sec_fn" value=""> 
            <input id="Tue" type="button" value="  +1 Slot  " onclick="show(this , 'tue3' , 'tue3');" /><br>
        </div>
		
		<div id="tue3" class="field">          
            <label></label>
            <input type="Text" class="time1"  name="tue_time3_start" id="tue_thr_st" value=""> 
            to
			<input type="Text"  class="time1" name="tue_time3_end" id="tue_thr_fn" value=""> 
        </div>
		<br>
		
		
		<!-- Wednesday -->
		<div class="field">
            <label>Wednesday </label> 
            <input type="Text" class="time1"  name="wed_time1_start" value=""> 
            to
			<input type="Text"  class="time1" name="wed_time1_end" value=""> 
            <input id="Wed" type="button" value="  +1 Slot  " onclick="show(this ,'wed2' , 'wed3');" /> 
        </div>
        <div id="wed2" class="field"> 
            <label></label>              
            <input type="Text"  class="time1" name="wed_time2_start" id="wed_sec_st" value="">
            to
			<input type="Text"  class="time1" name="wed_time2_end" id="wed_sec_fn" value="">
            <input id="Wed" type="button" value="  +1 Slot  " onclick="show(this ,'wed3' , 'wed3');" />
		</div>
		<div id="wed3" class="field"> 
            <label></label>              
            <input type="Text"  class="time1" name="wed_time3_start" id="wed_thr_st" value="">
            <input type="Text"  class="time1" name="wed_time3_end" id="wed_thr_fn" value="">
        </div>
		<br>
		
		
		<!-- Thursday -->
		<div class="field">
            <label>Thursday </label>
            <input type="Text"  class="time1" name="thu_time1_start" value="">
            to
			<input type="Text"  class="time1" name="thu_time1_end" value="">
            <input id="Thu" type="button" value="  +1 Slot  " onclick="show(this , 'thu2' , 'thu3');" />
        </div>
        <div id="thu2" class="field"> 
            <label></label>
            <input type="Text" class="time1"  name="thu_time2_start" id="thu_sec_st" value="">
            to
			<input type="Text"  class="time1" name="thu_time2_end" id="thu_sec_fn" value="">
            <input id="Thu" type="button" value="  +1 Slot  " onclick="show(this , 'thu3' , 'thu3');" />
		</div>
			<div id="thu3" class="field"> 
            <label></label>
            <input type="Text" class="time1"  name="thu_time3_start" id="thu_thr_st" value="">
            to
			<input type="Text"  class="time1" name="thu_time3_end" id="thu_thr_fn" value="">
			</div>
		<br>
	  
	  
		<!-- Friday -->
		<div class="field">
            <label>Friday </label>
            <input type="Text"  class="time1" name="fri_time1_start" value="">
            to
			<input type="Text" class="time1"  name="fri_time1_end" value="">
            <input id="Fri" type="button" value="  +1 Slot  " onclick="show(this , 'fri2' , 'fri3');" />
        </div>
			<div id="fri2" class="field"> 
            <label></label>
            <input type="Text"  class="time1" name="fri_time2_start" id="fri_sec_st" value="">
            to
			<input type="Text"  class="time1" name="fri_time2_end" id="fri_sec_fn" value="">
			<input id="Fri" type="button" value="  +1 Slot  " onclick="show(this , 'fri3' , 'fri3');" />
		</div>
		<div id="fri3" class="field"> 
            <label></label>
            <input type="Text"  class="time1" name="fri_time3_start" id="fri_thr_st" value="">
            <input type="Text"  class="time1" name="fri_time3_end" id="fri_thr_fn" value=""><br>
        </div>
		</table>    
	</div>
    <br>
		
		<!-- Saturday -->
		<div class="field">
             <label>Saturday </label> 
             <input type="Text"  class="time1" name="sat_time1_start" value=""> 
             to
			 <input type="Text"  class="time1" name="sat_time1_end" value=""> 
             <input id="Fri" type="button" value="  +1 Slot  " onclick="show(this , 'sat2' , 'sat3');" /><br>
        </div>
        <div id="sat2" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sat_time2_start" id="sat_sec_st" value=""> 
             to
			 <input type="Text"  class="time1" name="sat_time2_end"  id="sat_sec_fn" value=""> 
             <input id="Fri" type="button" value="  +1 Slot  " onclick="show(this , 'sat3' , 'sat3');" /><br>
		</div>
		<div id="sat3" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sat_time3_start" id="sat_thr_st" value=""> 
             <input type="Text"  class="time1" name="sat_time3_end"  id="sat_thr_fn" value=""> <br>
            
		</div>
		<br>  
		
		
		<!-- Sunday -->
		<div class="field">
             <label>Sunday </label> 
             <input type="Text" class="time1"  name="sun_time1_start" value=""> 
             to
			 <input type="Text"  class="time1" name="sun_time1_end" value=""> 
             <input id="clickMe" type="button" value="  +1 Slot  " onclick="show(this ,'sun2' , 'sun3');" /><br>
        </div>
        <div id="sun2" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sun_time2_start" id="sun_sec_st" value=""> 
             to
			 <input type="Text"  class="time1" name="sun_time2_end"  id="sun_sec_fn" value=""> 
             <input id="clickMe" type="button" value="  +1 Slot  " onclick="show(this ,'sun3' , 'sun3');" /><br>
		</div>
		<div id="sun3" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sun_time3_start" id="sun_thr_st" value=""> 
             <input type="Text"  class="time1" name="sun_time3_end"  id="sun_thr_fn" value=""> <br>
            
		</div>
		<br>
		<br>
		<div class="wrapper">
			<label></label>
			<label><input type="submit" name="save" class="Submit" /></label>
			<label></label>
			<label><input type="reset" name="cancel" value="Reset" class="submit" /></label>
			
		</div>
    </fieldset>
    <br><br><br><br>
</form>
</div>
<br><br><br><br>