 <?php echo "<div><br><br><span class=navigation_link1>You are here: </sapn><a href=adminindex.php?page=adminhome class="."navigation_link> Home&nbsp&nbsp;&raquo; </a> Change Password  </div>"; ?>

<br>

<div class="errors">
    <?php require 'dbconnect.php';

if(array_key_exists('save', $_POST))
{
	if ($_POST['password0']==="")
	{
		echo "<li>Current password field is empty";
	}
   else if($_POST['password1']==="" )
        echo "<li>passwords do not match";
  else if( $_POST['password1']!=$_POST['password2'])
   {
       echo "<li>passwords do not match";
   }
   else
   {
	   $admin   = $_SESSION['id'];
	   $query   =  "select password from admin where id='$admin'";   
       $result  = mysql_query($query) or die(mysql_error());
	   $row    = mysql_fetch_array($result);
	   
	   if ($_POST['password0'] == $row['password'] )
       {
			$p=$_POST['password1'];
            $query   =  "update admin set password='$p' where id='$admin'";   
			$result  = mysql_query($query) or die(mysql_error());
			echo "<li>Password updated successfully";
       }
	   else
	   {
			echo "<li>Current password don't match";
	   }
      
   }


} 
        ?>
</div>
<div class=course_options>
<div class="center">

<form name="Change" action="#" method="POST" onsubmit="return pass(this)">
    <fieldset>
        <div class="field">
            <label>Current Password</label>
            <input type="password" name="password0" value="" />
        </div>
		<div class="field">
            <label>New Password</label>
            <input type="password" name="password1" value="" />
        </div>
        <div class="field">
            <label>Re-Type Password</label>
            <input type="password" name="password2" value="" />
        </div>
        <div class="field">
		
        <input type="reset" name="cancel" value="Clear" class="submit" />
		<input type="submit" name="save" class="Submit" value="Change"/>
        
        </div>
    </fieldset>
</form>
</div></div>