<?php echo "<div><br><br><span class=navigation_link1>You are here: </sapn><a href=adminindex.php?page=adminhome class="."navigation_link> Home&nbsp&nbsp;&raquo; </a><a href=adminindex.php?page=manage_course class="."navigation_link> Manage Courses&nbsp&nbsp;&raquo; </a> Edit Course   </div>"; ?>

<br>

<div class=course_options>
<div class="errors"><ul>
<?php require 'dbconnect.php';

$empty_string_init = "\"    \" ";

$sun_count   = 0;   
$mon_count   = 0;   
$tue_count   = 0;
$wed_count   = 0;
$thu_count   = 0;
$fri_count   = 0;
$sat_count   = 0;

if(array_key_exists('save', $_POST))
{
$sun1_start  = ( $_POST['sun_time1_start'] != "" ) ? $_POST['sun_time1_start'] : $empty_string_init;
$sun1_end    = ( $_POST['sun_time1_end']   != "" ) ? $_POST['sun_time1_end']   : $empty_string_init;
$sun2_start  = ( $_POST['sun_time2_start'] != "" ) ? $_POST['sun_time2_start'] : $empty_string_init;
$sun2_end    = ( $_POST['sun_time2_end']   != "" ) ? $_POST['sun_time2_end']   : $empty_string_init;
   
$mon1_start  = ( $_POST['mon_time1_start'] != "" ) ? $_POST['mon_time1_start'] : $empty_string_init;
$mon1_end    = ( $_POST['mon_time1_end']   != "" ) ? $_POST['mon_time1_end']   : $empty_string_init;
$mon2_start  = ( $_POST['mon_time2_start'] != "" ) ? $_POST['mon_time2_start'] : $empty_string_init;
$mon2_end    = ( $_POST['mon_time2_end']   != "" ) ? $_POST['mon_time2_end']   : $empty_string_init;

$tue1_start  = ( $_POST['tue_time1_start'] != "" ) ? $_POST['tue_time1_start'] : $empty_string_init;
$tue1_end  = ( $_POST['tue_time1_end']     != "" ) ? $_POST['tue_time1_end']   : $empty_string_init;
$tue2_start  = ( $_POST['tue_time2_start'] != "" ) ? $_POST['tue_time2_start'] : $empty_string_init;
$tue2_end  = ( $_POST['tue_time2_end']     != "" ) ? $_POST['tue_time2_end']   : $empty_string_init;

$wed1_start  = ( $_POST['wed_time1_start'] != "" ) ? $_POST['wed_time1_start'] : $empty_string_init;
$wed1_end  = ( $_POST['wed_time1_end']     != "" ) ? $_POST['wed_time1_end']   : $empty_string_init;
$wed2_start  = ( $_POST['wed_time2_start'] != "" ) ? $_POST['wed_time2_start'] : $empty_string_init;
$wed2_end  = ( $_POST['wed_time2_end']     != "" ) ? $_POST['wed_time2_end']   : $empty_string_init;

$thu1_start  = ( $_POST['thu_time1_start'] != "" ) ? $_POST['thu_time1_start'] : $empty_string_init;
$thu1_end  = ( $_POST['thu_time1_end']     != "" ) ? $_POST['thu_time1_end']   : $empty_string_init;
$thu2_start  = ( $_POST['thu_time2_start'] != "" ) ? $_POST['thu_time2_start'] : $empty_string_init;
$thu2_end  = ( $_POST['thu_time2_end']     != "" ) ? $_POST['thu_time2_end']   : $empty_string_init;

$fri1_start  = ( $_POST['fri_time1_start'] != "" ) ? $_POST['fri_time1_start'] : $empty_string_init;
$fri1_end  = ( $_POST['fri_time1_end']     != "" ) ? $_POST['fri_time1_end']   : $empty_string_init;
$fri2_start  = ( $_POST['fri_time2_start'] != "" ) ? $_POST['fri_time2_start'] : $empty_string_init;
$fri2_end  = ( $_POST['fri_time2_end']     != "" ) ? $_POST['fri_time2_end']   : $empty_string_init;

$sat1_start  = ( $_POST['sat_time1_start'] != "" ) ? $_POST['sat_time1_start'] : $empty_string_init;
$sat1_end    = ( $_POST['sat_time1_end']   != "" ) ? $_POST['sat_time1_end']   : $empty_string_init;
$sat2_start  = ( $_POST['sat_time2_start'] != "" ) ? $_POST['sat_time2_start'] : $empty_string_init;
$sat2_end    = ( $_POST['sat_time2_end']   != "" ) ? $_POST['sat_time2_end']   : $empty_string_init;

$index = array(
                $sun1_start , $sun1_end , $sun2_start , $sun2_end ,
                $mon1_start , $mon1_end , $mon2_start , $mon2_end ,
                $tue1_start , $tue1_end , $tue2_start , $tue2_end ,
                $wed1_start , $wed1_end , $wed2_start , $wed2_end ,
                $thu1_start , $thu1_end , $thu2_start , $thu2_end ,
                $fri1_start , $fri1_end , $fri2_start , $fri2_end ,
                $sat1_start , $sat1_end , $sat2_start , $sat2_end
              );
$day   = array ($sun_count , $mon_count , $tue_count , $wed_count , $thu_count , $fri_count , $sat_count);

$i=0;   //  for index array = 7 * 4 = 28 
$j=0;   //  for day array   = 7

while ( $i  < 28 )
{
    //if scheule one has class
    if (( $index[$i] != $empty_string_init ) and ($index[$i+1] != $empty_string_init)) 
    {
        $day[$j]++;
    }

    //if scheule two has class
    if (( $index[$i+2] != $empty_string_init ) and ($index[$i+3] != $empty_string_init)) 
    {
        $day[$j]++;
    }
    
    $i = $i + 4;
    $j = $j + 1 ;
}

$sun_count = $day[0];
$mon_count = $day[1];
$tue_count = $day[2];
$wed_count = $day[3];
$thu_count = $day[4];
$fri_count = $day[5];
$sat_count = $day[6];

echo "<br>";

$sun = "Sunday";
$mon = "Monday";
$tue = "Tuesday";
$wed = "Wednesday";
$thu = "Thursday";
$fri = "Friday";
$sat = "Saturday";

$c_id   = $_POST['courseID'];
$c_nm   = $_POST['Name'];
$fac_id = $_POST['FacultyID'];
$st_dt  = $_POST['StartDate'];
$fn_dt  = $_POST['FinishDate'];

//checking if the course has been already registered or not
$query = "SELECT *
          FROM course_details
          WHERE course_id = '$c_id' 
         ";
$result = mysql_query($query) ;
$row    = mysql_fetch_array($result);

//if entry in table fails : i.e. course already exists or already registered
if (is_null($row))
{
    echo $c_nm . "  (   " .$c_id . "    )   " .     "<br><li>Not already registered</li>";
    echo "<br>For registering go to ADD COURSE";
}
else
{
    //updating course_details
    $query_cd = "   
                UPDATE course_details   
                SET course_name='$c_nm', id_no='$fac_id',starting_date = '$st_dt' , finishing_date = '$fn_dt'
                WHERE course_id='$c_id';
                ";
    $result_cd = mysql_query($query_cd);
    if (!$result_cd)
    {
        echo "Error in updating course_details";
    }
    else
    {
        //updating course_schedule
       
        //for Sunday
        $weekday = $sun;
        $c = $sun_count;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$sun1_start',time1_end='$sun1_end',time2_start='$sun2_start',time2_end='$sun2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Monday
        $weekday = $mon;
        $c       = $mon_count ;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$mon1_start',time1_end='$mon1_end',time2_start='$mon2_start',time2_end='$mon2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Tuesday
        $weekday = $tue;
        $c       = $tue_count ;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$tue1_start',time1_end='$tue1_end',time2_start='$tue2_start',time2_end='$tue2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Wednesday
        $weekday = $wed;
        $c       = $wed_count ;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$wed1_start',time1_end='$wed1_end',time2_start='$wed2_start',time2_end='$wed2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Thursday
        $weekday = $thu;
        $c       = $thu_count  ;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$thu1_start',time1_end='$thu1_end',time2_start='$thu2_start',time2_end='$thu2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Friday
        $weekday = $fri;
        $c = $fri_count ;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$fri1_start',time1_end='$fri1_end',time2_start='$fri2_start',time2_end='$fri2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
        
        //for Saturday
        $weekday = $sat;
        $c       = $sat_count;
        $query1 =   "
                        UPDATE course_schedule
                        SET time1_start = '$sat1_start',time1_end='$sat1_end',time2_start='$sat2_start',time2_end='$sat2_end',count='$c'
                        WHERE course_id='$c_id' AND day='$weekday'   
                    ";
        
        $result1 = mysql_query($query1);
        
        if (!$result1)
        {
            echo "Erron in updating schedule for ".$weekday;
        }
    }
    
    
}unset($_POST['save']);}?>  


    


<form name="add" action="#" method="post" id="add_course" onsubmit="return validation(this)">
    <fieldset>
    <div id="left">
  
        <div class="field">
             <label>Course ID</label> 
             <?php 
                        $query = "
                                    SELECT course_name,course_id  
                                    FROM  course_details
                                    ";
                        $result = mysql_query($query) or die(mysql_error());                     
             ?>
             
             <select name="courseID" id="edit_courseid" onchange="show_edit_details()">
             <?php                      
                        while ($row = mysql_fetch_array($result))
                        {
                              echo "<option value=".$row['course_id']."> ". $row['course_id']."->". $row['course_name'] ."  </option>";
                        }
             ?>
             </select> 
             
        </div>
        <br><br>
        <br>
        
        <div class="field">
             <label>Course Name</label> 
             <input type="text" name="Name" id="Course_Name"  />
                
             
        </div>
        
        <br>
              
        <div class="field">
             <label>Faculty ID</label> 
            
              <?php 
                        $query = "
                                    SELECT id ,name  
                                    FROM  faculty f , registered r
                                    WHERE id = id_no ;
                                    ";
                        $result = mysql_query($query) or die(mysql_error());
                       
                        ?>
             
             <select name="FacultyID" id="FacultyID" >
                <?php
                        
                        while ($row = mysql_fetch_array($result))
                        {
                              echo "<option value=".$row['id']."> ". $row['name'] ."  </option>";
                        }
                 ?>
             </select> 
        </div><br><br>
        
        
        <br>
        
        
        <div class="field">
             <label>Start Date</label> 
             <input id="Start_Date" type="Text" name="StartDate" value="" class="datepicker"> 
        </div>
        
        
        <br>
        
        
        <div class="field">
             <label>Finish Date</label> 
             <input type="Text" id="Finish_Date" name="FinishDate" value="" class="datepicker"> 
        </div>
        
        
        <br>
      </div>
      <br> 
     
      
      
      <div >
          <p> Schedule for the whole week </p>
          <br>
          
          
          <div class="field">
            
             <label>DAY </label> 
             
             <label> FROM </label>
             &nbsp;&nbsp;&nbsp;<label1></label1>
             <label>TO<label>
          </div>
          
      <br>
          
      
          <div class="field">
            
             <label>Monday </label> 
             <input type="Text" class="time1"  name="mon_time1_start" value="" id="mon_fir_st"> 
             <input type="Text" class="time1"  name="mon_time1_end" value="" id="mon_fir_fn"> 
             <input id="Mon" type="button" value="  +1 Slot  " onclick="show(this ,'mon2','mon3');" /><br>
          </div>
          <div id="mon2" class="field">
              <label></label>
             <input type="Text" class="time1" name="mon_time2_start" id="mon_sec_st" value=""> 
             <input type="Text" class="time1"  name="mon_time2_end"  id="mon_sec_fn" value="">
             <input id="Mon" type="button" value="  +1 Slot  " onclick="show(this ,'mon3','mon3');" /><br>
		  </div>
		  <div id="mon3" class="field">
              <label></label>
             <input type="Text" class="time1" name="mon_time3_start" id="mon_thr_st" value=""> 
             <input type="Text" class="time1"  name="mon_time3_end"  id="mon_thr_fn" value=""> <br>
            
		  </div>
      <br>  <label></label><label1></label1>
            <input type="button" name="copy_slots" id="copy_slots" value=" Copy for other slots " onclick="copy();"/>
      <br><br>
      <div class="field">
            
             <label>Tuesday </label> 
             <input type="Text" name="tue_time1_start" value="" class="time1" id="tue_fir_st"> 
             <input type="Text"  class="time1" name="tue_time1_end" value="" id="tue_fir_fn"> 
             <input id="Tue" type="button" value="  +1 Slot  " onclick="show(this , 'tue2' , 'tue3');" /><br> 
             </div>
          <div id="tue2" class="field">          
              <label></label>
             <input type="Text" class="time1"  name="tue_time2_start" id="tue_sec_st" value=""> 
             <input type="Text"  class="time1" name="tue_time2_end" id="tue_sec_fn" value=""> 
             <input id="Tue" type="button" value="  +1 Slot  " onclick="show(this , 'tue3' , 'tue3');" /><br>
          </div>
		  <div id="tue3" class="field">          
              <label></label>
             <input type="Text" class="time1"  name="tue_time3_start" id="tue_thr_st" value=""> 
             <input type="Text"  class="time1" name="tue_time3_end" id="tue_thr_fn" value=""> 
            
          </div>
      <br>
      <div class="field">
            
             <label>Wednesday </label> 
             <input type="Text" class="time1"  name="wed_time1_start" value="" id="wed_fir_st"> 
             <input type="Text"  class="time1" name="wed_time1_end" value="" id="wed_fir_fn"> 
             <input id="Wed" type="button" value="  +1 Slot  " onclick="show(this ,'wed2' , 'wed3');" /> 
            </div>
          <div id="wed2" class="field"> 
            <label></label>              
            <input type="Text"  class="time1" name="wed_time2_start" id="wed_sec_st" value="">
            <input type="Text"  class="time1" name="wed_time2_end" id="wed_sec_fn" value="">
            <input id="Wed" type="button" value="  +1 Slot  " onclick="show(this ,'wed3' , 'wed3');" />
		  </div>
		  <div id="wed3" class="field"> 
            <label></label>              
            <input type="Text"  class="time1" name="wed_time3_start" id="wed_thr_st" value="">
            <input type="Text"  class="time1" name="wed_time3_end" id="wed_thr_fn" value="">
          </div>
      <br>
      <div class="field">
            <label>Thursday </label>
            <input type="Text"  class="time1" name="thu_time1_start" value="" id="thu_fir_st">
            <input type="Text"  class="time1" name="thu_time1_end" value="" id="thu_fir_fn">
             <input id="Thu" type="button" value="  +1 Slot  " onclick="show(this , 'thu2' , 'thu3');" />
             </div>
          <div id="thu2" class="field"> 
             <label></label>
            <input type="Text" class="time1"  name="thu_time2_start" id="thu_sec_st" value="">
            <input type="Text"  class="time1" name="thu_time2_end" id="thu_sec_fn" value="">
            <input id="Thu" type="button" value="  +1 Slot  " onclick="show(this , 'thu3' , 'thu3');" />
		  </div>
		  <div id="thu3" class="field"> 
             <label></label>
            <input type="Text" class="time1"  name="thu_time3_start" id="thu_thr_st" value="">
            <input type="Text"  class="time1" name="thu_time3_end" id="thu_thr_fn" value="">
          </div>
      <br>
      <div class="field">
            <label>Friday </label>
            <input type="Text"  class="time1" name="fri_time1_start" value="" id="fri_fir_st">
            <input type="Text" class="time1"  name="fri_time1_end" value="" id="fri_fir_fn">
            <input id="Fri" type="button" value="  +1 Slot  " onclick="show(this , 'fri2' , 'fri3');" />
            </div>
          <div id="fri2" class="field"> 
            <label></label>
              <input type="Text"  class="time1" name="fri_time2_start" id="fri_sec_st" value="">
            <input type="Text"  class="time1" name="fri_time2_end" id="fri_sec_fn" value="">
			<input id="Fri" type="button" value="  +1 Slot  " onclick="show(this , 'fri3' , 'fri3');" />
		  </div>
		  <div id="fri3" class="field"> 
            <label></label>
              <input type="Text"  class="time1" name="fri_time3_start" id="fri_thr_st" value="">
            <input type="Text"  class="time1" name="fri_time3_end" id="fri_thr_fn" value=""><br>
          </div>
       
      </div>
      <br>
      <div class="field">
            
             <label>Saturday </label> 
             <input type="Text"  class="time1" name="sat_time1_start" value="" id="sat_fir_st"> 
             <input type="Text"  class="time1" name="sat_time1_end" value="" id="sat_fir_fn"> 
             <input id="Fri" type="button" value="  +1 Slot  " onclick="show(this , 'sat2' , 'sat3');" /><br>
          </div>
          <div id="sat2" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sat_time2_start" id="sat_sec_st" value=""> 
             <input type="Text"  class="time1" name="sat_time2_end"  id="sat_sec_fn" value=""> 
             <input id="Fri" type="button" value="  +1 Slot  " onclick="show(this , 'sat3' , 'sat3');" /><br>
		  </div>
		  <div id="sat3" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sat_time3_start" id="sat_thr_st" value=""> 
             <input type="Text"  class="time1" name="sat_time3_end"  id="sat_thr_fn" value=""> <br>
            
      </div>
      <br>  
      <div class="field">
            
             <label>Sunday </label> 
             <input type="Text" class="time1"  name="sun_time1_start" value="" id="sun_fir_st"> 
             <input type="Text"  class="time1" name="sun_time1_end" value="" id="sun_fir_fn">  
             <input id="clickMe" type="button" value="  +1 Slot  " onclick="show(this ,'sun2' , 'sun3');" /><br>
          </div>
          <div id="sun2" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sun_time2_start" id="sun_sec_st" value=""> 
             <input type="Text"  class="time1" name="sun_time2_end"  id="sun_sec_fn" value=""> 
             <input id="clickMe" type="button" value="  +1 Slot  " onclick="show(this ,'sun3' , 'sun3');" /><br>
      </div>
	  <div id="sun3" class="field">
              <label></label>
             <input type="Text"  class="time1" name="sun_time3_start" id="sun_thr_st" value=""> 
             <input type="Text"  class="time1" name="sun_time3_end"  id="sun_thr_fn" value=""> <br>
            
      </div>
	  
      <br><br>
      
	  <div class="wrapper">
            <label></label>
            <label><input type="submit" name="save" class="Submit" /></label>
            <label><input type="submit" name="cancel" value="Cancel" class="submit" /></label>
            
      </div>
    </fieldset>

    </form>
	</div>
</div>