
 <?php echo "<div><br><br><span class=navigation_link1>You are here: </sapn><a href=adminindex.php?page=adminhome class="."navigation_link> Home&nbsp&nbsp;&raquo; </a> Manage Courses   </div>"; ?>

<br><br>

<div class=course_options>
<a href="adminindex.php?page=add"> Add course </a><br>
<a href="adminindex.php?page=edit2"> Edit course </a><br>
<a href="adminindex.php?page=delete_course"> Delete course </a><br>
</div>